{
 "title": "Xylem - Network Analyzer",
 "time": { "from": "now-30s", "to": "now" },
 "panels": [
  {
   "title": "System Information",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT host, ip, internet, CONCAT(memory,' %') as memory, CONCAT(cpu,' %') as cpu FROM grafanadb.systeminfo LIMIT 1000000000000000000 "
    }
   ]
  },
  { "title": "Main Record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "All Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT time, ttl, size, alert FROM grafanadb.packets LIMIT 1000000000000000000 "
    }
   ]
  },
  {
   "title": "TCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT COUNT(proto) as TCP FROM grafanadb.packets WHERE proto='tcp'"
    }
   ]
  },
  {
   "title": "ARP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT COUNT(proto) as ARP FROM grafanadb.packets WHERE proto='arp'"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT COUNT(proto) as 'Total Packets Received' FROM grafanadb.packets"
    }
   ]
  },
  {
   "title": "UDP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT COUNT(proto) as UDP FROM grafanadb.packets WHERE proto='udp'"
    }
   ]
  },
  {
   "title": "Protocol Frequency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT\r\n    SUM(CASE WHEN proto = 'tcp' THEN 1 ELSE 0 END) AS TCP,\r\n    SUM(CASE WHEN proto = 'udp' THEN 1 ELSE 0 END) AS UDP,\r\n    SUM(CASE WHEN proto = 'icmp' THEN 1 ELSE 0 END) AS ICMP,\r\n    SUM(CASE WHEN proto = 'arp' THEN 1 ELSE 0 END) AS ARP\r\nFROM grafanadb.packets;"
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT COUNT(proto) as ICMP FROM grafanadb.packets WHERE proto='icmp'"
    }
   ]
  },
  {
   "title": "Alert",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT COUNT(alert) FROM grafanadb.packets WHERE alert = '1' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Attack Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 13 },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT time, concat(src_ip,' > ',dst_ip), serial, attack FROM grafanadb.packets WHERE NOT attack = 'safe'"
    }
   ]
  },
  {
   "title": "Malicious Concentration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT \r\n    time,\r\n    SUM(alert) OVER (ORDER BY time) AS Alert \r\nFROM \r\n    grafanadb.packets \r\nORDER BY \r\n    time"
    }
   ]
  },
  { "title": "Map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Threat Location",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 20, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "grafanadb",
     "rawSql": "SELECT * FROM grafanadb.geo LIMIT 9999999"
    }
   ]
  }
 ]
}